#!/usr/bin/env python3
"""Convert one or more image files into embedded encoded byte arrays for ESP-IDF builds."""

from __future__ import annotations

import argparse
import re
from dataclasses import dataclass
from pathlib import Path

from PIL import Image


@dataclass
class ImageRecord:
    name: str
    symbol: str
    width: int
    height: int
    data: bytes


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert image files into C source/header with encoded file byte arrays."
    )
    parser.add_argument(
        "--input",
        type=Path,
        action="append",
        required=True,
        help="Input image path (.png/.jpg/.jpeg). Can be provided multiple times.",
    )
    parser.add_argument("--output-c", type=Path, required=True, help="Output .c file")
    parser.add_argument("--output-h", type=Path, required=True, help="Output .h file")
    return parser.parse_args()


def to_identifier(name: str) -> str:
    ident = re.sub(r"[^a-zA-Z0-9_]", "_", name)
    ident = re.sub(r"_+", "_", ident).strip("_")
    if not ident:
        ident = "img"
    if ident[0].isdigit():
        ident = f"img_{ident}"
    return ident.lower()


def emit_header(path: Path) -> None:
    content = (
        "/* Auto-generated by scripts/pngs_to_c_arrays.py */\n"
        "#ifndef DIGIT_TEST_IMAGES_DATA_H_\n"
        "#define DIGIT_TEST_IMAGES_DATA_H_\n\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "#ifdef __cplusplus\n"
        'extern "C" {\n'
        "#endif\n\n"
        "typedef struct {\n"
        "    const char *name;\n"
        "    int width;\n"
        "    int height;\n"
        "    const uint8_t *data;\n"
        "    size_t data_len;\n"
        "} digit_test_image_t;\n\n"
        "extern const digit_test_image_t g_digit_test_images[];\n"
        "extern const size_t g_digit_test_images_count;\n\n"
        "#ifdef __cplusplus\n"
        "}\n"
        "#endif\n\n"
        "#endif  /* DIGIT_TEST_IMAGES_DATA_H_ */\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii")


def format_bytes(data: bytes) -> list[str]:
    lines: list[str] = []
    row: list[str] = []
    for idx, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) == 16:
            suffix = "," if idx < len(data) - 1 else ""
            lines.append("    " + ", ".join(row) + suffix)
            row = []
    if row:
        lines.append("    " + ", ".join(row))
    return lines


def emit_source(path: Path, header_name: str, images: list[ImageRecord]) -> None:
    lines = [
        "/* Auto-generated by scripts/pngs_to_c_arrays.py */",
        f'#include "{header_name}"',
        "",
    ]

    for image in images:
        symbol = image.symbol
        data = image.data
        lines.append(f"static const uint8_t {symbol}[] = {{")
        lines.extend(format_bytes(data))
        lines.append("};")
        lines.append("")

    lines.append("const digit_test_image_t g_digit_test_images[] = {")
    for image in images:
        lines.append(
            "    {"
            f' "{image.name}", '
            f"{image.width}, "
            f"{image.height}, "
            f"{image.symbol}, "
            f"sizeof({image.symbol}) "
            "},"
        )
    lines.append("};")
    lines.append(
        "const size_t g_digit_test_images_count = sizeof(g_digit_test_images) / sizeof(g_digit_test_images[0]);"
    )
    lines.append("")

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")


def load_image(path: Path) -> tuple[int, int, bytes]:
    with Image.open(path) as image:
        width, height = image.size
    data = path.read_bytes()
    return width, height, data


def main() -> None:
    args = parse_args()

    seen: set[str] = set()
    images: list[ImageRecord] = []

    for input_path in args.input:
        if not input_path.exists():
            raise SystemExit(f"Input image not found: {input_path}")

        width, height, data = load_image(input_path)

        stem = to_identifier(input_path.stem)
        symbol = f"g_digit_test_img_{stem}"
        suffix = 1
        while symbol in seen:
            symbol = f"g_digit_test_img_{stem}_{suffix}"
            suffix += 1
        seen.add(symbol)

        images.append(
            ImageRecord(
                name=input_path.name,
                symbol=symbol,
                width=width,
                height=height,
                data=data,
            )
        )

    if not images:
        raise SystemExit("No input images provided")

    emit_header(args.output_h)
    emit_source(args.output_c, args.output_h.name, images)

    print(f"count={len(images)}")
    for image in images:
        print(
            f"image={image.name} size={image.width}x{image.height} bytes={len(image.data)} symbol={image.symbol}"
        )
    print(f"header={args.output_h}")
    print(f"source={args.output_c}")


if __name__ == "__main__":
    main()
