#!/usr/bin/env python3
"""Convert a .tflite file into C source/header arrays for ESP-IDF builds."""

from __future__ import annotations

import argparse
from pathlib import Path


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Convert a .tflite file into C source/header with a byte array symbol."
    )
    parser.add_argument("--input", type=Path, required=True, help="Input .tflite file")
    parser.add_argument("--output-c", type=Path, required=True, help="Output .c file")
    parser.add_argument("--output-h", type=Path, required=True, help="Output .h file")
    parser.add_argument(
        "--symbol",
        type=str,
        default="g_model_data",
        help="Array symbol name (default: g_model_data)",
    )
    return parser.parse_args()


def emit_header(path: Path, symbol: str) -> None:
    guard = f"{symbol.upper()}_H_"
    content = (
        "/* Auto-generated by scripts/tflite_to_c_array.py */\n"
        "#ifndef "
        + guard
        + "\n"
        "#define "
        + guard
        + "\n\n"
        "#include <stddef.h>\n"
        "#include <stdint.h>\n\n"
        "extern const unsigned char "
        + symbol
        + "[];\n"
        "extern const size_t "
        + symbol
        + "_len;\n\n"
        "#endif  /* "
        + guard
        + " */\n"
    )
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="ascii")


def emit_source(path: Path, header_name: str, symbol: str, data: bytes) -> None:
    lines = [
        "/* Auto-generated by scripts/tflite_to_c_array.py */",
        f'#include "{header_name}"',
        "",
        f"const unsigned char {symbol}[] = {{",
    ]

    row: list[str] = []
    for idx, b in enumerate(data):
        row.append(f"0x{b:02x}")
        if len(row) == 12:
            suffix = "," if idx < len(data) - 1 else ""
            lines.append("    " + ", ".join(row) + suffix)
            row = []

    if row:
        lines.append("    " + ", ".join(row))

    lines.extend(
        [
            "};",
            f"const size_t {symbol}_len = sizeof({symbol});",
            "",
        ]
    )

    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="ascii")


def main() -> None:
    args = parse_args()

    model_path = args.input
    if not model_path.exists():
        raise SystemExit(f"Input model not found: {model_path}")

    raw = model_path.read_bytes()
    if len(raw) == 0:
        raise SystemExit(f"Input model is empty: {model_path}")

    emit_header(args.output_h, args.symbol)
    emit_source(args.output_c, args.output_h.name, args.symbol, raw)

    print(f"input={model_path}")
    print(f"bytes={len(raw)}")
    print(f"header={args.output_h}")
    print(f"source={args.output_c}")
    print(f"symbol={args.symbol}")


if __name__ == "__main__":
    main()
