/* Auto-generated by scripts/pngs_to_c_arrays.py */
#ifndef DIGIT_TEST_IMAGES_DATA_H_
#define DIGIT_TEST_IMAGES_DATA_H_

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    const char *name;
    int width;
    int height;
    const uint8_t *data;
    size_t data_len;
} digit_test_image_t;

extern const digit_test_image_t g_digit_test_images[];
extern const size_t g_digit_test_images_count;

#ifdef __cplusplus
}
#endif

#endif  /* DIGIT_TEST_IMAGES_DATA_H_ */
