/* Auto-generated by scripts/tflite_to_c_array.py */
#ifndef G_MNIST_TINY_INT8_MODEL_H_
#define G_MNIST_TINY_INT8_MODEL_H_

#include <stddef.h>
#include <stdint.h>

extern const unsigned char g_mnist_tiny_int8_model[];
extern const size_t g_mnist_tiny_int8_model_len;

#endif  /* G_MNIST_TINY_INT8_MODEL_H_ */
